### ISSUE TITLE
GTK Problems, potential parsing issue.

### ISSUE THREAD

**Issue by devnod** [r0x0r/pywebview-react-boilerplate#6]
First, let me commend you on the incredible work! I thought this wasn't even possible at the time...
.
I was able to get my React bundle loaded and working (almost fully) but that was with QT only..

I actually run Slackware Linux and have both qt and gtk installed, but it defaulted to QT which means massive libraries were downloaded. It works - but I really need to get it working with GTK as well given my project currently uses it primarily. 

Currently I have all the requirements installed which were going to be done via the apt-get command.. but it fails to run, returns "GTK cannot be loaded". 

Not only do I have gtk 1, 2, and 3 installed, I also have both webkitgtk and webkitgtk3 installed (from source.)

I was hoping you might be able to point me in the right direction...

In regards to the QT version, the only issue I noticed was that &nbsp; does not return a space, but rather an unidentified character..

Again, thanks for the incredible work!

**Comment by r0x0r** [comment]
Sounds like you do not have GTK dependencies installed. What you have to install varies from system to system. This might help https://pywebview.flowrl.com/guide/installation.html#dependencies <https://pywebview.flowrl.com/guide/installation.html#dependencies>

To debug this issue set PYWEBVIEW_LOG=debug variable before running your script and see if it produces more error output

**Comment by devnod** [comment]
Ok I've been able to find the issue..

It's nomenclature mostly.. rather than installing a "webkitgtk" package on Slackware, what is actually needed is the "webkit2gtk" package. 

If installing on -current (which very few use the last stable at this point), the following packages are needed (and obtainable via SlackBuilds from Ponce's repo)

bubble, virtualenv (you knew already), hyphen, libseccomp, woff2, libwebp, xdg-dbus-proxy and lastly - webkit2gtk.

For those who want to use the pyinstaller function, they'll need to do so via the the python3 version of pip rather than installing via SlackBuild: "pip3 install pyinstaller" suffices. 

There are a few CSS elements that seem to be different but that appears to just be a difference between webkit and the way a browser handles it.

Thanks for the response! Hopefully my experiences can help others who want to use it on a source-based distro :)

Kudos again for the work! I'll make sure to include your name in my project release for thanks, and I'll send you a sourceforge link later when its in use :)
