### ISSUE TITLE
Huge distribution file sizes

### ISSUE THREAD

**Issue by altonova** [r0x0r/pywebview-react-boilerplate#8]
In multiple Linux environments I've tried building the basic boilerplate, following the README instructions (below).  dist/ folder always ends up being multiple GB (ex. 1.2G, 2.7G, 4.0G) which is not a usable distributable size.

npm run init
npm run build

**Comment by r0x0r** [comment]
I have no experience with freezing on Linux, but it appears that a freezer bundles unneeded dependencies (the whole QT or GTK package or maybe even both). To debug this issue you have several options
1) Analyze your frozen package to see what is being bundled
2) Try uninstalling some dependencies
3) Change a freezer
4) Sometimes using built-in Python vs a separate Python installation makes a difference

Good luck.
