### ISSUE TITLE
Static folder to dynamically load images or files using the pywebview-react-boilerplate

### ISSUE THREAD

**Issue by Jonny-P** [r0x0r/pywebview-react-boilerplate#9]
### Here are the steps in what I am trying to achieve using the [pywebview-react-boilerplate](https://github.com/r0x0r/pywebview-react-boilerplate):

1. I click on a button in the Web GUI to execute the python script
2. The python script generates a _**image.png**_ file and saves it to the _**Output**_ folder.
3. The Web GUI loads the _**image.png**_ from the _**Output**_ folder and displays it.

I am struggling with step 3, the python script after generating the **_image.png_** returns the file path to the JavaScript that updates the front end, but it doesn't work.. 

#### c) Is it possible to load images or files dynamicaly from a folder outside the project folder like: 

> _"C:\Users\Descktop\Output\image.png"_

**Comment by r0x0r** [comment]
The easiest way would be probably is to use pywebview's built-in http server and save files to the folder shared by the http server. 

https://pywebview.flowrl.com/blog/pywebview3.html#built-in-http-server

**Comment by Jonny-P** [comment]
Before anything else, thank you for your previous response, really appreciate your help here.

I tried making a simple HTML page with the  pywebview's built-in server like you suggested, but I can't load any image outside the DIR where the "index.html" is.. and that is not helpful for what I am trying to accomplish.

**Could you please make a demo on how could I dynamically load images from any folder on my PC with a simple Pywebview HTML page setup example?**

**Comment by r0x0r** [comment]
As I see it you should either save dynamic files to the same directory as your html is served (or its subdirectory) or use JS API to serve dynamic files from whatever location.
